### ISSUE TITLE
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

### ISSUE THREAD

**Issue by melihovv** [KernelFolla/dumpmyrepos#1]
I type `dumpmyrepos --config=config.yml --dry-run` in my console

It give me such output
```
Traceback (most recent call last):
  File "/home/melihovv/.local/bin/dumpmyrepos", line 11, in <module>
    load_entry_point('dumpmyrepos==0.1', 'console_scripts', 'dumpmyrepos')()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/cli.py", line 42, in main
    conf.dump_all()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 36, in dump_all
    repositories = self.get_repositories()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 23, in get_repositories
    res = pool.map_async(lambda x: x.get_repositories(), accounts).get(999999)
  File "/home/melihovv/.local/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

After I change config.py how it said in this [answer](http://stackoverflow.com/a/8805244/5469133)

add function `work`:
```python
def work(x):
    return x.get_repositories()
```
and change this line
```python
res = pool.map_async(lambda x: x.get_repositories(), accounts).get(999999)
```
to this
```python
res = pool.map_async(work, accounts).get(999999)
```
it outputs me the following errors:
```
Traceback (most recent call last):
  File "/home/melihovv/.local/bin/dumpmyrepos", line 11, in <module>
    load_entry_point('dumpmyrepos==0.1', 'console_scripts', 'dumpmyrepos')()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/cli.py", line 42, in main
    conf.dump_all()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 39, in dump_all
    repositories = self.get_repositories()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 26, in get_repositories
    res = pool.map_async(work, accounts).get(999999)
  File "/home/melihovv/.local/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
multiprocess.pool.MaybeEncodingError: Error sending result: '[[<dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9be5df38>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9be5dfc8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e70e0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e7200>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e72d8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e7368>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e73f8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e7488>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e7518>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5e75f0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9becfc20>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9be5d248>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8998>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c89e0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8a70>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8b00>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8b90>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8c20>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8cb0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c8d88>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c5cb0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c5c68>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b5c83b0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4de878>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4de908>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4de9e0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4deab8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4deb90>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4dec20>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4decb0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4de7e8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b437050>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4370e0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4371b8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b437290>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4373b0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b437440>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4374d0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b437560>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b4375f0>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b47a560>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b47a638>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b47aa70>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b419a28>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b419ab8>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b419b90>, <dumpmyrepos.services.bitbucket.BitbucketRepository instance at 0x7f6d9b419c20>]]'. Reason: 'PicklingError("Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed",)'
```
Can you help me, please?
Ubuntu 16.04, python 2.7.12

**Comment by KernelFolla** [comment]
Hello @melihovv 
i've just tried with ubuntu 16.04 and python 2.7.12, same version and no errors.

Please share your config.yml replacing your credentials with fake data, i need to reproduce to fix.

**Comment by melihovv** [comment]
Error is in my bitbucket credentials. Without bitbucket credentials all work.
Initially I used bitbucket client_key and client_secret. OAuth consumer has following permissions: read account, read projects and read repositories. But it throws the errors shown above.
Now I try to use bitbucket username and password. My config:
```yml
  bitbucket:
    type: bitbucket
    auth:
      #client_key: ***********
      #client_secret: ********
      username: melihovv
      password: *******
      client_email: amelihovv@ya.ru
      #server_base_uri: https://bitbucket.org
```
The error is:
```
Traceback (most recent call last):
  File "/home/melihovv/.local/bin/dumpmyrepos", line 11, in <module>
    load_entry_point('dumpmyrepos==0.1', 'console_scripts', 'dumpmyrepos')()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/cli.py", line 42, in main
    conf.dump_all()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 39, in dump_all
    repositories = self.get_repositories()
  File "/home/melihovv/.local/lib/python2.7/site-packages/dumpmyrepos/config.py", line 26, in get_repositories
    res = pool.map_async(work, accounts).get(999999)
  File "/home/melihovv/.local/lib/python2.7/site-packages/multiprocess/pool.py", line 567, in get
    raise self._value
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bitbucket.org/2.0/repositories/melihovv?role=member
```
What do I need to specify in server_base_url?

**Comment by KernelFolla** [comment]
There are companies using private instances of bitbucket, for typical usage you can leave it commented/removed or the default https://bitbucket.org

**Comment by melihovv** [comment]
Perhaps it is because two-step verification is setup in my bitbucket account. Do you have two-step verification in your account?

**Comment by KernelFolla** [comment]
Indeed on bitbucket I use client_key and client_secret to solve this issue, otherwise you should disabe double step verification or validate the machine.

from bitbucket website:
Some applications that rely on basic authentication may no longer work as expected. While Bitbucket recommends that third-party application developers switch to using OAuth, there are still many applications where https may be the only option. Application-specific passwords allow you to create a password for apps such as SourceTree and Bamboo so that you can use Git, Mercurial, and the API over HTTPS as needed.
First, check that your application is set to use SSH for authentication with Bitbucket. If you need to use the Bitbucket API over HTTPS, use application passwords.

**Comment by melihovv** [comment]
Thanks!)
